### ISSUE TITLE
Does not detect when keys are pressed

### ISSUE THREAD

**Issue by nickknw** [calesce/redux-slider-monitor#13]
As the title describes - cannot hide/show the monitor with ctrl-h. 
I notice you check for `process.env.IS_BROWSER`, which isn't set when I check it in my app. Is that a node-specific thing - would it be possible to make the keyboard check a bit less environment specific? The LogMonitor in devtools checks `typeof window !== 'undefined'` - maybe that instead?

**Comment by calesce** [comment]
Hmmm. Yeah, I should probably just replicate what LogMonitor does for consistency. In fact, once DevTools 3.0 is out (and I release 1.0 of this monitor) I'll defer the visibility stuff to [dock monitor](https://github.com/gaearon/redux-devtools-dock-monitor). I'd still like to have specific shortcuts for the slider, so I'll try to fix that up tomorrow. Thanks!

**Comment by nickknw** [comment]
How's this going? Looking forward to pulling down the change.

**Comment by calesce** [comment]
Fix is out in ```redux-slider-monitor@0.6.4``` on npm.

**Comment by nickknw** [comment]
Wonderful, thanks!
