### ISSUE TITLE
Clicking on footer links do not create new state in TODO MVC Demo

### ISSUE THREAD

**Issue by petr001** [calesce/redux-slider-monitor#17]
Hi,
when I click on filtering links, no new state is created, so you can't "time travel". Isn't it a buggy behaviour?

**Comment by gaearon** [comment]
In this particular version of the example [filter is kept in the component state](https://github.com/calesce/redux-slider-monitor/blob/c2b842b971930b6036b7bf5c92436a8ce081f52b/examples/todomvc/components/MainSection.js#L20). This is why it's not in the history.

**Comment by calesce** [comment]
Yeah, that piece of state is not tracked by Redux, so DevTools can't know about it.
