### ISSUE TITLE
Bottom padding

### ISSUE THREAD

**Issue by zalmoxisus** [calesce/redux-slider-monitor#18]
Could you please publish changes to npm? The current `1.0.0` has bottom padding for the elements except slider bar, so it goes bellow the arrows (I guess it is because I don't use DockMonitor). It is fixed here, but not released yet.

**Comment by calesce** [comment]
I went ahead and published as 1.0.1. I'm still not happy with the layout, though, so I'll leave this issue open. I'll make sure to test without DockMonitor for future changes.

**Comment by zalmoxisus** [comment]
Hey @calesce,

I'm hacking some reusable components for building Redux DevTools monitors (specifically for the extension, but most of them will work for vanilla DevTools as well, except that they will use only the default theme there).

[Here's a demo of the slider](https://zalmoxisus.github.io/remotedev-monitor-components/?knob-Title=Hello%20Tooltip&knob-play%20title=Play&knob-Big=true&knob-primary=true&knob-max=100&knob-Disabled=false&knob-disabled=false&knob-withValue=false&knob-value=80&knob-min=0&knob-Label=Hello%20Button&knob-label=Slider%20label&selectedKind=Toolbar&selectedStory=with%20slider&full=0&down=1&left=1&panelRight=1&downPanel=kadirahq%2Fstorybook-addon-knobs). From the right panel choose `THEME`, and you'll be able to change to default/material theme and color schemes.

Please let me know if you're still interested in maintaining and develop this repository further, have time to contribute, and find using my components suitable for Slider Monitor. If you want to keep it as is, I'll go with a separate one. Otherwise, I'd try to contribute it back.

In Redux DevTools Extension `3.0`, apart from regular monitors, we'll have monitors for managing the reports, so if we move that part from `remotedev-slider`, we can deprecate it in favour of `redux-slider-monitor`. Again, the question is if you want to add additional complexity here.

**Comment by calesce** [comment]
Thanks @zalmoxisus, this looks great. What changes do you propose for this module? I'm interested in supporting DevTools Extension.

**Comment by zalmoxisus** [comment]
Except the UI, the most signifiant change, I guess, will be that instead of showing the current action id, we'll show action type (as slider label). I'll cut a beta of that lib in about a week and will submit a pr with implementation here.

**Comment by calesce** [comment]
👍 This does need UI enhancements, especially the slider handle.

> instead of showing the current action id, we'll show action type (as slider label)

Maybe we can show both, or at least have it be configurable? I like being able to see total actions/index of current action.

**Comment by zalmoxisus** [comment]
The problem is that, due to using of `maxAge`, we don't have the real index and count of actions. We can show only the correct action id, but, again it's ambiguous, as the total number of actions we can time travel is not the same as the number of dispatched actions.

We have an option [to see the slider value](https://zalmoxisus.github.io/remotedev-monitor-components/?knob-Title=Hello%20Tooltip&knob-play%20title=Play&knob-formData=%7B%22name%22%3A%22Chuck%20Norris%22%2C%22age%22%3A75%2C%22bio%22%3A%22Roundhouse%20kicking%20asses%20since%201940%22%2C%22password%22%3A%22noneed%22%2C%22integerRange%22%3A52%7D&knob-Big=true&knob-primary=true&knob-uiSchema=%7B%22name%22%3A%7B%22ui%3Aautofocus%22%3Atrue%7D%2C%22age%22%3A%7B%22ui%3Awidget%22%3A%22updown%22%7D%2C%22bio%22%3A%7B%22ui%3Awidget%22%3A%22textarea%22%7D%2C%22password%22%3A%7B%22ui%3Awidget%22%3A%22password%22%2C%22ui%3Ahelp%22%3A%22Hint%3A%20Make%20it%20strong%21%22%7D%2C%22date%22%3A%7B%22ui%3Awidget%22%3A%22alt-datetime%22%7D%2C%22multipleChoicesList%22%3A%7B%22ui%3Awidget%22%3A%22checkboxes%22%7D%2C%22numberEnumRadio%22%3A%7B%22ui%3Awidget%22%3A%22radio%22%2C%22ui%3Aoptions%22%3A%7B%22inline%22%3Atrue%7D%7D%2C%22integerRange%22%3A%7B%22ui%3Awidget%22%3A%22range%22%7D%7D&knob-max=100&knob-Disabled=false&knob-disabled=false&knob-withValue=false&knob-schema=%7B%22title%22%3A%22Example%20form%22%2C%22description%22%3A%22A%20simple%20form%20example.%22%2C%22type%22%3A%22object%22%2C%22required%22%3A%5B%22name%22%5D%2C%22properties%22%3A%7B%22name%22%3A%7B%22type%22%3A%22string%22%2C%22title%22%3A%22Full%20name%22%7D%2C%22age%22%3A%7B%22type%22%3A%22integer%22%2C%22title%22%3A%22Age%22%7D%2C%22bio%22%3A%7B%22type%22%3A%22string%22%2C%22title%22%3A%22Bio%22%7D%2C%22password%22%3A%7B%22type%22%3A%22string%22%2C%22title%22%3A%22Password%22%2C%22minLength%22%3A3%7D%2C%22multipleChoicesList%22%3A%7B%22type%22%3A%22array%22%2C%22title%22%3A%22A%20multiple%20choices%20list%22%2C%22items%22%3A%7B%22type%22%3A%22string%22%2C%22enum%22%3A%5B%22foo%22%2C%22bar%22%2C%22fuzz%22%5D%7D%2C%22uniqueItems%22%3Atrue%7D%2C%22numberEnum%22%3A%7B%22type%22%3A%22number%22%2C%22title%22%3A%22Number%20enum%22%2C%22enum%22%3A%5B1%2C2%2C3%5D%7D%2C%22numberEnumRadio%22%3A%7B%22type%22%3A%22number%22%2C%22title%22%3A%22Number%20enum%22%2C%22enum%22%3A%5B1%2C2%2C3%5D%7D%2C%22integerRange%22%3A%7B%22title%22%3A%22Integer%20range%22%2C%22type%22%3A%22integer%22%2C%22minimum%22%3A42%2C%22maximum%22%3A100%7D%7D%7D&knob-value=80&knob-min=0&knob-submitText=Submit&knob-Label=Hello%20Button&knob-label=Slider%20label&selectedKind=Form&selectedStory=default&full=0&down=1&left=1&panelRight=1&downPanel=kadirahq%2Fstorybook-addon-knobs), but for our case we could show action id just in the parenthesis near the action type.

**Comment by calesce** [comment]
> If you meant the new slider

No, I meant the one in this repo :wink: I much prefer the new slider's handle.
