### ISSUE TITLE
Maybe another monitor?

### ISSUE THREAD

**Issue by lapanoid** [calesce/redux-slider-monitor#2]
I saw your interest with replaying app like cerebral can. This works especially cool with your slider monitor, but I think that export/import of actions/state can be used for a lot of things not only for this use case. So maybe we can collaborate to make redux-export-import-monitor happen, what do you think?

**Comment by calesce** [comment]
@lapanoid I'm very interested! I agree in that making it a separate repo would probably be best. I discuss it a little bit [here](https://github.com/gaearon/redux-devtools/pull/39). Basically, DevTools would need to allow for monitors to dispatch the lifted actions itself to make the "import" part possible (unless I'm missing something :grinning:)

**Comment by calesce** [comment]
Closing because https://github.com/lapanoid/redux-import-export-monitor
