### ISSUE TITLE
Unknown prop `fit` on <svg> tag

### ISSUE THREAD

**Issue by jacktrades** [calesce/redux-slider-monitor#24]
I'm getting a warning in Chrome about an unknown property:

    Warning: Unknown prop `fit` on <svg> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
        in svg (created by SliderButton)

Looks like it's coming from the [SliderButton](https://github.com/calesce/redux-slider-monitor/blob/master/src/SliderButton.js#L23)

**Comment by calesce** [comment]
Thanks for the heads up! Fixed in `1.0.7`.
