### ISSUE TITLE
Replay in `live` gone?

### ISSUE THREAD

**Issue by amannn** [calesce/redux-slider-monitor#25]
I noticed the `live` feature is gone. This was really helpful for me. Is there a particular reason why this was removed?

![screen shot 2016-12-09 at 15 58 17](https://cloud.githubusercontent.com/assets/4038316/21053145/6a539182-be28-11e6-8df6-df40858789b4.png)

**Comment by calesce** [comment]
I think the Redux DevTools extension is using a different slider component. cc @zalmoxisus

**Comment by zalmoxisus** [comment]
Yes, as @calesce noted. It is using [`remotedev-slider`](https://github.com/zalmoxisus/remotedev-slider). Doesn't `.5x` have the same effect as `live`?

I might be misunderstanding the role of `live`, but if there will be no delay (and assuming that the state is applied synchronously) how we'll see the intermediate states?

Also unlike vanilla Redux DevTools, the extension is in different process from the client app. So, it will always take some milliseconds to communicate (to serialize and parse the message).

**Comment by amannn** [comment]
Oh, sorry about the issue then. I'll continue the discussion in the other repo.
