### ISSUE TITLE
warning.js?8a56:36 Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

### ISSUE THREAD

**Issue by gabrielmicko** [calesce/redux-slider-monitor#31]

**Comment by keqingrong** [comment]
Need to update outdated dependencies? The devui@1.0.0-1 has migrated to prop-types package.

**Comment by gabrielmicko** [comment]
I see, probably my mistake, right?

**Comment by jhen0409** [comment]
Sorry I missed this issue. 😔

It should fixed in https://github.com/zalmoxisus/devui/pull/16, just released as `1.0.0-1` .
