### ISSUE TITLE
Cannot read property 'state' of undefined

### ISSUE THREAD

**Issue by zdychacek** [calesce/redux-slider-monitor#9]
Hi,

when there's no state sequence recorded yet and I click play button I get en error:

`Cannot read property 'state' of undefined`

This error is also in your example: https://calesce.github.io/redux-slider-monitor/

O.

**Comment by calesce** [comment]
Fixed by e661169aac50a90484c53b3369006380b581f363. Working on fixing the example now. Thanks!
